In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Path: taller_integrador.ipynb
# FunciÃ³n para leer el archivo de datos

def xls_to_pd(xls_file):
    df = pd.read_excel(xls_file)
    return df


df = xls_to_pd('Taller.xls').set_index('FECHA VENTA').drop(['Unnamed: 0', "Unnamed: 9"], axis=1)
df.columns
display(df)

## Check duplicates and Nan values

print("Nan values: ", df.isnull().sum().sum())
print("Duplicated values: ", df.duplicated().sum())

## Print all unique values of "MES" column

print("Unique values of 'MES' column: ", df['MES'].unique())

,NUMERO FACTURA,DESPACHO,MES,RUT CLIENTE,NOMBRE,ADUANA,DECLARACION,GASTO POR VENTA,HONORARIOS,EJECUTIVO
FECHA VENTA,,,,,,,,,,
2016-01-01,123471,163452,ENERO,81675600 -6,COMERCIALIZADORA S.A.,VALPARAISO,IMPORTACION,43428,12710,VICTOR QUEZADA
2016-01-02,123472,163451,ENERO,81675600 -6,COMERCIALIZADORA S.A.,VALPARAISO,IMPORTACION,43428,12181,VICTOR QUEZADA
2016-01-03,123473,163450,ENERO,81675600 -6,COMERCIALIZADORA S.A.,VALPARAISO,IMPORTACION,43428,11400,VICTOR QUEZADA
2016-01-04,123474,163449,ENERO,81675600 -6,COMERCIALIZADORA S.A.,VALPARAISO,IMPORTACION,43428,10975,VICTOR QUEZADA
2016-01-05,123447,163504,ENERO,81148200 -5,FERROCARRIL DE ANTOFAGASTA A BOLIVIA,METROPOLITANA,IMPORTACION,12332,24663,JORGE MENAY
...,...,...,...,...,...,...,...,...,...,...
2018-02-27,124607,164201,DICIEMBRE,81148200 -5,FERROCARRIL DE ANTOFAGASTA A BOLIVIA,METROPOLITANA,IMPORTACION,12332,37151,JORGE MENAY
2018-02-28,124597,164766,DICIEMBRE,76423701 -3,LOI CHILE SPA,METROPOLITANA,IMPORTACION,15415,75384,SERGIO JOFRE
2018-03-01,124596,163750,DICIEMBRE,76466068 -4,SOC. CONC. NUEVO PUDAHUEL S.A,METROPOLITANA,IMPORTACION,12332,36995,DOMINIQUE GARMENDIA PINTO
2018-03-02,20261,162439,DICIEMBRE,81148200 -5,FERROCARRIL DE ANTOFAGASTA A BOLIVIA,ANTOFAGASTA,EXPORTACION,12332,24663,JORGE MENAY
2018-03-03,20259,164280,DICIEMBRE,76264035 -K,BOPP CHILE S.A.,LOS ANDES,EXPORTACION,40077,52409,DOMINIQUE GARMENDIA PINTO

Nan values:  0
Duplicated values:  0
Unique values of 'MES' column:  ['ENERO' 'FEBRERO' 'MARZO' 'ABRIL' 'MAYO' 'JUNIO' 'JULIO' 'AGOSTO'
 'SEPTIEMBRE' 'OCTUBRE' 'NOVIEMBRE' 'DICIEMBRE']